DROP TABLE IF EXISTS contributions;

CREATE TABLE contributions (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    giver TEXT,
    receiver TEXT,
    amount MONEY,
    contribution_date DATE
);

INSERT INTO contributions (giver, receiver, amount, contribution_date) VALUES ('Jason', 'Compassion Intl', '$100', '2022-01-04');
INSERT INTO contributions (giver, receiver, amount, contribution_date) VALUES ('Jason', 'Compassion Intl', '$100', '2022-02-04');
INSERT INTO contributions (giver, receiver, amount, contribution_date) VALUES ('Jason', 'Compassion Intl', '$100', '2022-03-04');
INSERT INTO contributions (giver, receiver, amount, contribution_date) VALUES ('Cameron', 'St. Judes Hospital', '$90.59', '2022-03-06');
INSERT INTO contributions (giver, receiver, amount, contribution_date) VALUES ('Cameron', 'Holy Cross Orthodox Church', '$130', '2022-01-22');